-- =========================================================
-- بيت الخبرات القانونية | Supabase production starter
-- نفّذ هذا الملف كاملًا في SQL Editor داخل مشروع Supabase.
-- =========================================================

create extension if not exists pgcrypto;

do $$ begin
  create type public.app_role as enum ('user','admin','content_manager','training_manager','services_manager','instructor');
exception when duplicate_object then null; end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role public.app_role not null default 'user',
  phone text,
  specialty text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique,
  category text not null default 'عام',
  type text not null default 'برنامج تدريبي',
  description text,
  hours integer not null default 1 check (hours > 0),
  sessions integer not null default 1 check (sessions > 0),
  mode text not null default 'حضوري',
  start_at timestamptz,
  end_at timestamptz,
  price numeric(10,2) not null default 0 check (price >= 0),
  status text not null default 'draft' check (status in ('draft','published','closed')),
  cover_url text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  progress integer not null default 0 check (progress between 0 and 100),
  status text not null default 'enrolled' check (status in ('pending','enrolled','completed','cancelled')),
  enrolled_at timestamptz not null default now(),
  unique(user_id, course_id)
);

create table if not exists public.certificates (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  course_id bigint references public.courses(id) on delete set null,
  certificate_number text not null unique,
  issued_at timestamptz not null default now(),
  pdf_url text,
  verification_hash text
);

create table if not exists public.experts (
  id bigint generated by default as identity primary key,
  full_name text not null,
  title text,
  bio text,
  specialties text[] not null default '{}',
  avatar_url text,
  is_published boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.content_items (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique,
  content_type text not null default 'article' check (content_type in ('article','research','guide','news','release')),
  excerpt text,
  body text,
  status text not null default 'draft' check (status in ('draft','published')),
  author_id uuid references public.profiles(id) on delete set null,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  event_type text not null default 'فعالية',
  description text,
  starts_at timestamptz,
  ends_at timestamptz,
  location text,
  registration_url text,
  status text not null default 'draft' check (status in ('draft','published','closed')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  service_type text not null,
  subject text not null,
  details text,
  status text not null default 'new' check (status in ('new','reviewing','in_progress','completed','rejected')),
  assigned_to uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  title text not null,
  body text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.favorites (
  user_id uuid not null references public.profiles(id) on delete cascade,
  entity_type text not null check (entity_type in ('course','content')),
  entity_id bigint not null,
  created_at timestamptz not null default now(),
  primary key(user_id, entity_type, entity_id)
);

create index if not exists idx_courses_status_start on public.courses(status,start_at);
create index if not exists idx_content_status_published on public.content_items(status,published_at);
create index if not exists idx_events_status_start on public.events(status,starts_at);
create index if not exists idx_enrollments_user on public.enrollments(user_id);
create index if not exists idx_requests_user on public.service_requests(user_id);

-- New-user profile trigger. Role is NEVER taken from the browser metadata.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, phone)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data->>'full_name',''), split_part(new.email,'@',1)),
    new.raw_user_meta_data->>'phone'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid()
      and role in ('admin','content_manager','training_manager','services_manager')
  );
$$;

create or replace function public.current_role()
returns public.app_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

-- updated_at helper
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

do $$ begin
  create trigger profiles_touch before update on public.profiles for each row execute procedure public.touch_updated_at();
exception when duplicate_object then null; end $$;
do $$ begin
  create trigger courses_touch before update on public.courses for each row execute procedure public.touch_updated_at();
exception when duplicate_object then null; end $$;
do $$ begin
  create trigger experts_touch before update on public.experts for each row execute procedure public.touch_updated_at();
exception when duplicate_object then null; end $$;
do $$ begin
  create trigger content_touch before update on public.content_items for each row execute procedure public.touch_updated_at();
exception when duplicate_object then null; end $$;
do $$ begin
  create trigger events_touch before update on public.events for each row execute procedure public.touch_updated_at();
exception when duplicate_object then null; end $$;
do $$ begin
  create trigger requests_touch before update on public.service_requests for each row execute procedure public.touch_updated_at();
exception when duplicate_object then null; end $$;

alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.enrollments enable row level security;
alter table public.certificates enable row level security;
alter table public.experts enable row level security;
alter table public.content_items enable row level security;
alter table public.events enable row level security;
alter table public.service_requests enable row level security;
alter table public.notifications enable row level security;
alter table public.favorites enable row level security;

-- Drop policies so this script can be re-run safely.
do $$ declare p record; begin
  for p in
    select schemaname, tablename, policyname from pg_policies
    where schemaname='public'
      and tablename in ('profiles','courses','enrollments','certificates','experts','content_items','events','service_requests','notifications','favorites')
  loop
    execute format('drop policy if exists %I on %I.%I',p.policyname,p.schemaname,p.tablename);
  end loop;
end $$;

-- Profiles
create policy profiles_select_own on public.profiles for select using (auth.uid()=id or public.is_admin());
create policy profiles_update_own on public.profiles for update using (auth.uid()=id or public.current_role()='admin') with check (auth.uid()=id or public.current_role()='admin');

-- Public catalogues + role-based management
create policy courses_public_read on public.courses for select using (status='published' or public.is_admin());
create policy courses_manage on public.courses for all using (
  public.current_role() in ('admin','training_manager')
) with check (
  public.current_role() in ('admin','training_manager')
);

create policy experts_public_read on public.experts for select using (is_published=true or public.is_admin());
create policy experts_manage on public.experts for all using (
  public.current_role() in ('admin','content_manager')
) with check (
  public.current_role() in ('admin','content_manager')
);

create policy content_public_read on public.content_items for select using (status='published' or public.is_admin());
create policy content_manage on public.content_items for all using (
  public.current_role() in ('admin','content_manager')
) with check (
  public.current_role() in ('admin','content_manager')
);

create policy events_public_read on public.events for select using (status='published' or public.is_admin());
create policy events_manage on public.events for all using (
  public.current_role() in ('admin','content_manager')
) with check (
  public.current_role() in ('admin','content_manager')
);

-- Enrollments
create policy enrollments_own_read on public.enrollments for select using (auth.uid()=user_id or public.current_role() in ('admin','training_manager'));
create policy enrollments_own_insert on public.enrollments for insert with check (auth.uid()=user_id);
create policy enrollments_training_manage on public.enrollments for update using (public.current_role() in ('admin','training_manager')) with check (public.current_role() in ('admin','training_manager'));
create policy enrollments_admin_delete on public.enrollments for delete using (public.current_role() in ('admin','training_manager'));

-- Certificates
create policy certificates_own_read on public.certificates for select using (auth.uid()=user_id or public.current_role() in ('admin','training_manager'));
create policy certificates_manage on public.certificates for all using (public.current_role() in ('admin','training_manager')) with check (public.current_role() in ('admin','training_manager'));

-- Service requests
create policy requests_own_read on public.service_requests for select using (auth.uid()=user_id or public.current_role() in ('admin','services_manager'));
create policy requests_own_insert on public.service_requests for insert with check (auth.uid()=user_id);
create policy requests_services_manage on public.service_requests for update using (public.current_role() in ('admin','services_manager')) with check (public.current_role() in ('admin','services_manager'));

-- Notifications
create policy notifications_own_read on public.notifications for select using (auth.uid()=user_id or public.current_role()='admin');
create policy notifications_own_update on public.notifications for update using (auth.uid()=user_id or public.current_role()='admin');
create policy notifications_admin_insert on public.notifications for insert with check (public.current_role()='admin');

-- Favorites
create policy favorites_own_all on public.favorites for all using (auth.uid()=user_id) with check (auth.uid()=user_id);

-- Storage bucket for public course/expert assets. Make it private if documents are sensitive.
insert into storage.buckets (id,name,public)
values ('bait-assets','bait-assets',true)
on conflict (id) do nothing;

create policy bait_assets_public_read on storage.objects for select using (bucket_id='bait-assets');
create policy bait_assets_authenticated_upload on storage.objects for insert with check (bucket_id='bait-assets' and auth.role()='authenticated');
create policy bait_assets_owner_update on storage.objects for update using (bucket_id='bait-assets' and owner_id::text=auth.uid()::text);
create policy bait_assets_owner_delete on storage.objects for delete using (bucket_id='bait-assets' and owner_id::text=auth.uid()::text);

-- ---------------------------------------------------------
-- First admin:
-- 1) Create the admin account normally from the website.
-- 2) Copy its UUID from Authentication > Users.
-- 3) Run:
-- update public.profiles set role='admin' where id='YOUR-USER-UUID';
-- ---------------------------------------------------------

-- Optional sample data (safe to delete/change):
insert into public.courses
(title,slug,category,type,description,hours,sessions,mode,start_at,price,status)
values
('الصياغة القانونية المتقدمة','advanced-legal-drafting','صياغة','برنامج تدريبي','من التأصيل النظامي إلى بناء النص القانوني المحكم، مع تطبيقات عملية.',15,5,'حضوري','2026-10-20 16:00:00+03',0,'published'),
('التحكيم التجاري: من الاتفاق إلى الحكم','commercial-arbitration','تحكيم','دورة متخصصة','رحلة عملية في أهم مراحل التحكيم التجاري وإدارة الملف التحكيمي.',12,4,'عن بُعد','2026-11-03 18:00:00+03',0,'published'),
('الحوكمة والامتثال للمنشآت','governance-compliance','حوكمة','برنامج مهني','مفاهيم وأدوات عملية لبناء منظومة الحوكمة والامتثال وإدارة المخاطر القانونية.',10,4,'حضوري','2026-11-18 16:00:00+03',0,'published')
on conflict (slug) do nothing;
